name: Build and Push Container Image

on:
  pull_request:
    paths:
      - versions.json
  push:
    branches:
      - main
    paths:
      - versions.json

jobs:
  versions:
    runs-on: ubuntu-latest

    outputs:
      toolsVersions: ${{ steps.versions.outputs.tools }}
      latestVersion: ${{ steps.versions.outputs.latest }}
      revision: ${{ steps.versions.outputs.revision}}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Parse versions.json"
        id: versions
        run: |
          toolsVersions=$(jq -c .tools versions.json)
          latestVersion=$(jq -r -c .latest versions.json)
          revision=$(jq -r -c .revision versions.json)

          echo 'tools=$toolsVersions' >> $GITHUB_OUTPUT
          echo 'tools=$toolsVersions'

          echo 'latest=$latestVersion' >> $GITHUB_OUTPUT
          echo 'latest=$latestVersion'

          echo 'revision=$revision' >> $GITHUB_OUTPUT
          echo 'revision=$revision'

      - name: "Confirm"
        run: |
          echo "${{ steps.versions.outputs.tools }}"
          echo "${{ steps.versions.outputs.latest }}"
          echo "${{ steps.versions.outputs.revision}}"

  build:
    runs-on: ubuntu-latest
    needs: versions
    strategy:
      matrix: ${{ fromJSON(needs.versions.outputs.toolsVersions) }}

    steps:
      - name: Log Inputs
        run: |
          echo "Kubectl Version: ${{ matrix.kubectl }}"
          echo "Helm Version: ${{ matrix.helm }}"
          echo "Powershell Version: ${{ matrix.powershell }}"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch names
        id: branch_names
        uses: OctopusDeploy/util-actions/current-branch-name@current-branch-name.0.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ARTIFACTORY_DOCKER_REPO_HOSTNAME }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        # Only log into Dockerhub on when using main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create Tag Version
        run: |
          kubernetesVersion="${{ matrix.kubectl }}"
          if [[ "${{steps.branch_names.outputs.branch_name}}" != "main" ]]
            then
            preRelease="-${{steps.branch_names.outputs.branch_name}}-$(date +'%Y%m%d%H%M%S')"
          fi

          revision="-${{ needs.versions.outputs.revision }}"

          tagVersion="${kubernetesVersion%'.'*}$revision$preRelease";
          echo "tagVersion=$tagVersion" >> $GITHUB_OUTPUT;
          echo "tagVersion=$tagVersion";

          allVersionsTag="${{ matrix.kubectl}}-${{ matrix.helm}}-${{matrix.powershell}}$revision"
          echo "allVersionsTag=$allVersionsTag" >> $GITHUB_OUTPUT;
          echo "allVersionsTag=$allVersionsTag";

        id: createTagVersion

      - name: Build and push for test
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "${{ secrets.ARTIFACTORY_DOCKER_REPO_HOSTNAME }}/octopusdeploy/kubernetes-agent-tools-base:${{ steps.createTagVersion.outputs.tagVersion }},${{ secrets.ARTIFACTORY_DOCKER_REPO_HOSTNAME }}/octopusdeploy/kubernetes-agent-tools-base:${{ steps.createTagVersion.outputs.allVersionsTag}}" 
          platforms: linux/amd64,linux/arm64
          build-args: |
            "KUBECTL_VERSION=${{ matrix.kubectl }}"
            "HELM_VERSION=${{ matrix.helm }}"
            "POWERSHELL_VERSION=${{ matrix.powershell }}"

      - name: Create production docker tags
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          artifactoryTags="${{ secrets.ARTIFACTORY_DOCKER_REPO_HOSTNAME }}/octopusdeploy/kubernetes-agent-tools-base:${{ steps.createTagVersion.outputs.tagVersion }},${{ secrets.ARTIFACTORY_DOCKER_REPO_HOSTNAME }}/octopusdeploy/kubernetes-agent-tools-base:${{ steps.createTagVersion.outputs.allVersionsTag}}"
          dockerhubTags="octopusdeploy/kubernetes-agent-tools-base:${{ steps.createTagVersion.outputs.tagVersion }},octopusdeploy/kubernetes-agent-tools-base:${{ steps.createTagVersion.outputs.allVersionsTag}}" 


          kubernetesVersion="${{ matrix.kubectl }}"
          if [[ "${{ needs.versions.outputs.latestVersion }}" == "${kubernetesVersion%'.'*}" ]]
            then
            artifactoryTags="$artifactoryTags,${{ secrets.ARTIFACTORY_DOCKER_REPO_HOSTNAME }}/octopusdeploy/kubernetes-agent-tools-base:latest"
            dockerhubTags="$dockerhubTags,octopusdeploy/kubernetes-agent-tools-base:latest"
          fi

          dockerTags="$artifactoryTags,$dockerhubTags"
          echo "dockerTags=$dockerTags" >> $GITHUB_OUTPUT;
          echo "dockerTags=$dockerTags";
        id: createProductionDockerTags

      - name: Build and push for production
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.createProductionDockerTags.outputs.dockerTags }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            "KUBECTL_VERSION=${{ matrix.kubectl }}"
            "HELM_VERSION=${{ matrix.helm }}"
            "POWERSHELL_VERSION=${{ matrix.powershell }}"
