on:
  workflow_dispatch:
  pull_request:
    paths:
    - versions.json
    - .github/workflows/test-deprecated-tags.yml

jobs:
  get_deprecated_tags:
    name: Get deprecated version final tags
    runs-on: ubuntu-latest
    
    outputs:
      deprecatedFinalTags: ${{ steps.tags.outputs.finalTags }}
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: parse versions.json
        id: tags
        run: |
          echo $(jq -c "[.deprecations | to_entries]" versions.json)
          echo $(jq -c "[.deprecations | to_entries | .[]]" versions.json)
          echo $(jq -c "[.deprecations | to_entries | .[].value]" versions.json)
          deprecatedFinalTags=$(jq -c "[.deprecations | to_entries | .[].value.finalTag]" versions.json)
          echo "finalTags=$deprecatedFinalTags" >> $GITHUB_OUTPUT
          echo "finalTags=$deprecatedFinalTags"

  test_docker_pull:
    name: Test via docker pull
    runs-on: ubuntu-latest
    needs: get_deprecated_tags
    strategy:
      matrix: 
        deprecatedTag: ${{ fromJSON(needs.get_deprecated_tags.outputs.deprecatedFinalTags) }}

    steps:
      - name: Log Inputs
        run: |
          echo "Deprecated Tag: ${{ matrix.deprecatedTag }}"

      - name: Attempt Docker Pull
        run: |
          docker pull octopusdeploy/kubernetes-agent-tools-base:${{matrix.deprecatedTag}}
