name: Test versions.json
on:
  workflow_dispatch:
  pull_request:
    paths:
    - versions.json
    - versions.schema.json
    - .github/workflows/test-deprecated-tags.yml

jobs:
  validate_json:
    name: Validate json against schema
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install json-spec
      - run: json validate --schema-file=versions.schema.json --document-file=versions.json

  get_deprecated_tags:
    name: Get deprecated version latest tags
    runs-on: ubuntu-latest
    needs: validate_json
    outputs:
      deprecatedVersionLatestTags: ${{ steps.tags.outputs.latestTags }}
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: parse versions.json
        id: tags
        run: |
          deprecatedLatestTags=$(jq -c "[.deprecations | to_entries | .[].value.latestTag]" versions.json)
          echo "latestTags=$deprecatedLatestTags" >> $GITHUB_OUTPUT
          echo "latestTags=$deprecatedLatestTags"

  test_docker_pull:
    name: Test via docker pull
    runs-on: ubuntu-latest
    needs: get_deprecated_tags
    strategy:
      matrix: 
        latestTag: ${{ fromJSON(needs.get_deprecated_tags.outputs.deprecatedVersionLatestTags) }}

    steps:
      - name: Log Inputs
        run: |
          echo "Deprecated Version Latest Tag: ${{ matrix.latestTag }}"

      - name: Attempt Docker Pull
        run: |
          docker pull octopusdeploy/kubernetes-agent-tools-base:${{matrix.latestTag}}
